A lot of logic for me.  Hope will be better later
js-tasks-ru/js-20220209_mironova-plus pull request #3
Opened 2022-02-24 13:49 UTC by gerry2923

2022-02-25 09:22 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-02-25 16:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-25 18:29 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        chartHeight = 50;
👍 good

2022-02-25 18:29 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        // сделать массив и добавить все туда
👍 good

2022-02-25 18:30 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let mapData = this.getColumnProps(data);
тут переменная `const`

2022-02-25 18:30 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        let htmlDataArray = [];
и тут переменная `const`

2022-02-25 18:32 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        mapData.forEach(item => htmlDataArray.push(`<div style="--value: ${item.value}" data-tooltip="${item.percent}"></div>`));
в данном случае цикл `forEach` и объявление переменной `htmlArray` следует заменить на вызов метода `map` - он как раз и вернет новый массив:
```
const htmlArray = mapData.map(item => {
  return `<div style="--value:${item.value} ...`
})
```

2022-02-25 18:32 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      initEventListeners () {
не оставляйте пустой метод, он пока нам не нужен

2022-02-25 18:32 UTC, dosandk commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +        const scale = 50 / maxValue;
```
50 - это `chartHeight`
```

2022-02-25 18:33 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    let el = document.querySelector('.notification');
`const el`

2022-02-25 18:33 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show (elem = document.body) {
👍 лайк за использование значения аргумента по умолчанию

2022-02-25 18:34 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if(el) {
вот тут следует подумать. Как проверить наличие на странице предыдущего нотификейшена не обращаясь к `document`?

2022-02-25 18:36 UTC, dosandk requested changes
подумайте как в компоненте `NotificationMessage` отказаться от обращения к DOM для проверки наличия элемента на странице. Подсказка: примените статическое свойство.

2022-02-26 08:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-26 08:49 UTC, gerry2923 commented on 04-oop-basic-intro-to-dom/1-column-chart/index.js
> +      initEventListeners () {
Не стала убирать этот пустой метод, потому что без него тест не проходит.

2022-02-26 16:30 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    for (let val of this.headerConfig) {
`const val`

2022-02-26 16:30 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    for ( let val of this.data) {
`const val`

2022-02-26 16:31 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +      arBody.push(`
подумайте, может лучше воспользоваться методом `map`?

2022-02-26 16:31 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  sort () {
функционал сортировки следует добавить

2022-02-26 16:31 UTC, dosandk requested changes
Задачу `SortableTable` следует закончить

2022-03-07 20:44 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-03-08 18:49 UTC, dosandk approved these changes
good 👍

2022-03-08 18:50 UTC, merged